backend:
  name: git-gateway
  branch: main # 나중에 깃허브에 연결할 브랜치 이름입니다.

# 이 부분은 나중에 사이트를 깃허브에 올리고 Netlify에 연결할 때 활성화합니다.
# local_backend: true

media_folder: "images/uploads" # 이미지 업로드 시 저장될 폴더
public_folder: "/images/uploads" # 이미지 파일을 불러올 때 사용할 경로

collections:
  - name: "blog" # 컬렉션의 고유 ID
    label: "블로그" # 관리자 페이지에 표시될 이름
    folder: "posts" # 실제 파일이 저장될 폴더
    create: true # 새 글 작성 허용
    slug: "{{fields.title}}" # 파일 이름을 게시물 제목으로 사용
    extension: "md" # 파일 확장자
    format: "frontmatter" # 제목, 날짜 등은 상단에, 본문은 아래에 저장
    fields: # 글 작성 시 사용할 입력 필드들
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" } 